// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyAspMvcBlog.Data;

#nullable disable

namespace MyAspMvcBlog.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240915174121_BlogSeeding")]
    partial class BlogSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyAspMvcBlog.Entities.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("blogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "This is my first blog",
                            Title = "My first blog"
                        },
                        new
                        {
                            Id = 2,
                            Content = "This is my second blog",
                            Title = "My second blog"
                        },
                        new
                        {
                            Id = 3,
                            Content = "This is my third blog",
                            Title = "My third blog"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
