// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyAspMvcPost.Data;

#nullable disable

namespace MyAspMvcPost.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240915193957_ChangeNameFromBlogsToPost")]
    partial class ChangeNameFromBlogsToPost
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyAspMvcPost.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReadTimeMinute")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "This is my first post",
                            Created = new DateTime(2024, 9, 16, 2, 39, 56, 301, DateTimeKind.Local).AddTicks(9458),
                            Image = "https://picsum.photos/200/300",
                            ReadTimeMinute = 5,
                            Title = "My first post",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "This is my second post",
                            Created = new DateTime(2024, 9, 16, 2, 39, 56, 301, DateTimeKind.Local).AddTicks(9478),
                            Image = "https://picsum.photos/200/300",
                            ReadTimeMinute = 5,
                            Title = "My second post",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Content = "This is my third post",
                            Created = new DateTime(2024, 9, 16, 2, 39, 56, 301, DateTimeKind.Local).AddTicks(9481),
                            Image = "https://picsum.photos/200/300",
                            ReadTimeMinute = 5,
                            Title = "My third post",
                            UserId = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
